use ts_rs::TS;

pub use prospero_protocol_rs::{
    API_VERSION, AgentKind, CONTENT_CHUNK_BYTES, ChangeEvent, CreateSession,
    DATABASE_QUEUE_CAPACITY, DatabaseHealth, EVENT_RETENTION, EventPage, EventQuery, Health,
    HealthPersistence, MAX_EVENT_BYTES, MAX_PAGE_BYTES, MAX_PAGE_ITEMS, RelayConnectionState,
    RelayRuntimeDeviceStatus, RelayRuntimeStatus, RenameSession, ResyncRequired, SessionHead,
    SessionKind, SessionLifecycle, SessionLookup, SessionLookupResult, SessionPage, SessionQuery,
    SessionStatus, SessionSummary, UpdateSession, WorkspaceHead, WorkspacePage, WorkspaceQuery,
};

pub use prospero_protocol_rs::{
    AgentQuestion, AgentSend, AttachmentInput, AutomationState, AutomationWorkspace, CancelTask,
    ContentHead, ContentPage, CreateTerminal, Dispatch, DispatchState, FileDiff, FsChunk,
    FsChunkQuery, FsContent, FsDone, FsEntry, FsListing, FsPathQuery, FsPathRequest, FsPutRequest,
    FsRenameRequest, FsWriteRequest, FsWritten, Gate, GateStatus, GitCommitRequest, GitDiffQuery,
    GitDiffResult, GitDone, GitFile, GitHistoryEntry, GitHistoryResult, GitStageRequest,
    GitStatusResult, MessageAttachment, MessageRole, PermissionDecision, ProjectSearchRequest,
    QuestionAnswer, QuestionDecision, QuestionOption, ResolveGate, Run, RunAutomation, RunSnapshot,
    RunStatus, SearchMatch, SearchResult, Task, TaskStatus, TerminalEvent, TerminalInput,
    TerminalPage, TerminalQuery, TerminalSize, TerminalSnapshot, TimelineBody,
    TimelineLookupResult, TimelinePage, TimelineQuery, TimelineRecord, TimelineTextPage,
    TimelineTextQuery, TimelineWrite, ToolState, WorkspaceSummaryResult, WorktreeAsset,
    WorktreeAssetKind, WorktreeAssetState, WorktreeCleanup, WorktreeInspection,
};

pub fn typescript() -> String {
    let config = ts_rs::Config::default();
    let declarations = [
        AgentKind::decl(&config),
        SessionKind::decl(&config),
        SessionLifecycle::decl(&config),
        SessionStatus::decl(&config),
        SessionHead::decl(&config),
        CreateSession::decl(&config),
        UpdateSession::decl(&config),
        SessionQuery::decl(&config),
        SessionPage::decl(&config),
        SessionSummary::decl(&config),
        WorkspaceQuery::decl(&config),
        WorkspaceHead::decl(&config),
        WorkspacePage::decl(&config),
        SessionLookup::decl(&config),
        SessionLookupResult::decl(&config),
        ChangeEvent::decl(&config),
        EventPage::decl(&config),
        crate::relay::RelayConnectionState::decl(&config),
        crate::relay::RelayRuntimeDeviceStatus::decl(&config),
        crate::relay::RelayRuntimeStatus::decl(&config),
        DatabaseHealth::decl(&config),
        HealthPersistence::decl(&config),
        Health::decl(&config),
        RenameSession::decl(&config),
        EventQuery::decl(&config),
        ResyncRequired::decl(&config),
        ContentHead::decl(&config),
        ContentPage::decl(&config),
        MessageRole::decl(&config),
        ToolState::decl(&config),
        FileDiff::decl(&config),
        QuestionOption::decl(&config),
        AgentQuestion::decl(&config),
        MessageAttachment::decl(&config),
        TimelineBody::decl(&config),
        TimelineRecord::decl(&config),
        TimelineWrite::decl(&config),
        TimelineQuery::decl(&config),
        TimelinePage::decl(&config),
        TimelineLookupResult::decl(&config),
        TimelineTextQuery::decl(&config),
        TimelineTextPage::decl(&config),
        CreateTerminal::decl(&config),
        TerminalSize::decl(&config),
        TerminalEvent::decl(&config),
        TerminalQuery::decl(&config),
        TerminalPage::decl(&config),
        TerminalInput::decl(&config),
        TerminalSnapshot::decl(&config),
        crate::agent::CreateAgentSession::decl(&config),
        crate::agent::CreateCrossModelChild::decl(&config),
        crate::agent::CrossModelChild::decl(&config),
        crate::agent::ResumeInput::decl(&config),
        crate::agent::ResumableConversation::decl(&config),
        crate::agent::ConversationSearchResult::decl(&config),
        crate::agent::AttachmentChunk::decl(&config),
        crate::agent::LaunchModelInfo::decl(&config),
        crate::agent::AgentPresetInfo::decl(&config),
        crate::agent::LaunchModelCatalog::decl(&config),
        crate::agent::AgentModelSelection::decl(&config),
        crate::agent::AgentModelSelectionResult::decl(&config),
        crate::agent::AgentControlResult::decl(&config),
        crate::agent::AgentCompactRequest::decl(&config),
        crate::agent::ApprovalPolicySelection::decl(&config),
        crate::agent::AgentModelCatalog::decl(&config),
        crate::agent::SessionAgentControls::decl(&config),
        crate::agent::AgentControlsProjection::decl(&config),
        AttachmentInput::decl(&config),
        AgentSend::decl(&config),
        crate::agent::QueuedMessage::decl(&config),
        crate::agent::AgentQueue::decl(&config),
        crate::agent::AgentQueues::decl(&config),
        crate::agent::UsageWindow::decl(&config),
        crate::agent::UsageDailyBucket::decl(&config),
        crate::agent::UsageReport::decl(&config),
        crate::agent::UsageAccount::decl(&config),
        crate::agent::UsageResult::decl(&config),
        PermissionDecision::decl(&config),
        QuestionAnswer::decl(&config),
        QuestionDecision::decl(&config),
        crate::agent::AgentModeSelection::decl(&config),
        crate::agent::AgentModeCatalog::decl(&config),
        crate::agent::AgentModeEntry::decl(&config),
        crate::agent::SubagentInfo::decl(&config),
        crate::agent::SubagentSnapshot::decl(&config),
        RunStatus::decl(&config),
        TaskStatus::decl(&config),
        DispatchState::decl(&config),
        GateStatus::decl(&config),
        crate::orchestration::MessageType::decl(&config),
        AutomationState::decl(&config),
        AutomationWorkspace::decl(&config),
        RunAutomation::decl(&config),
        Run::decl(&config),
        Task::decl(&config),
        Dispatch::decl(&config),
        Gate::decl(&config),
        crate::orchestration::OrchMessage::decl(&config),
        RunSnapshot::decl(&config),
        crate::orchestration::GraphNodeInput::decl(&config),
        crate::orchestration::CreateRunGraph::decl(&config),
        crate::orchestration::ApplyTaskGraph::decl(&config),
        crate::orchestration::GraphMutationResult::decl(&config),
        crate::orchestration::DispatchTask::decl(&config),
        crate::orchestration::SettleDispatch::decl(&config),
        crate::orchestration::AbandonDispatch::decl(&config),
        crate::orchestration::CompleteRun::decl(&config),
        crate::orchestration::AbandonRun::decl(&config),
        CancelTask::decl(&config),
        crate::orchestration::CreateGate::decl(&config),
        ResolveGate::decl(&config),
        crate::orchestration::PostMessage::decl(&config),
        crate::orchestration::MarkMessages::decl(&config),
        crate::orchestration::SettleOutcome::decl(&config),
        crate::orchestration::RecoveryReport::decl(&config),
        WorktreeAssetKind::decl(&config),
        WorktreeAssetState::decl(&config),
        WorktreeInspection::decl(&config),
        WorktreeCleanup::decl(&config),
        WorktreeAsset::decl(&config),
        crate::orchestration::WorktreeCleanupResult::decl(&config),
        crate::orchestration::CreateRun::decl(&config),
        crate::orchestration::CreateTask::decl(&config),
        crate::orchestration::DeleteRun::decl(&config),
        crate::orchestration::RunDeletionResult::decl(&config),
        crate::orchestration::StartAutomation::decl(&config),
        crate::orchestration::StartWorker::decl(&config),
        crate::orchestration::StopWorker::decl(&config),
        crate::orchestration::WorkerStartOutcome::decl(&config),
        crate::orchestration::InspectWorktree::decl(&config),
        crate::orchestration::CleanupWorktree::decl(&config),
        crate::skills::Skill::decl(&config),
        crate::skills::SkillSuggestion::decl(&config),
        crate::schedules::ScheduledAgentTaskKind::decl(&config),
        crate::schedules::ScheduledAgentTaskStatus::decl(&config),
        crate::schedules::ScheduledAgentTask::decl(&config),
        crate::schedules::StatusScheduledAgentTask::decl(&config),
        crate::schedules::ScheduleCreate::decl(&config),
        crate::schedules::ScheduleUpdate::decl(&config),
        crate::schedules::ScheduleId::decl(&config),
        crate::schedules::ScheduleRunResult::decl(&config),
        crate::plugins::PluginServiceMode::decl(&config),
        crate::plugins::PluginServiceHealth::decl(&config),
        crate::plugins::PluginServiceStatus::decl(&config),
        crate::plugins::PluginServiceManifest::decl(&config),
        crate::plugins::ProsperoPluginManifest::decl(&config),
        crate::plugins::PublicPluginService::decl(&config),
        crate::plugins::PublicProsperoPlugin::decl(&config),
        crate::plugins::PluginDiscoveryError::decl(&config),
        crate::plugins::PublicPluginDiscoveryResult::decl(&config),
        crate::plugins::PluginServiceExit::decl(&config),
        crate::plugins::PluginServiceState::decl(&config),
        crate::plugins::PluginServiceLogFiles::decl(&config),
        crate::plugins::PluginServiceView::decl(&config),
        crate::plugins::PluginServiceList::decl(&config),
        crate::accounts::AccountStatus::decl(&config),
        crate::accounts::AccountCapabilities::decl(&config),
        crate::accounts::ModelCapabilities::decl(&config),
        crate::accounts::profile::ModelCapabilitySupportValue::decl(&config),
        crate::accounts::ModelCapabilitySupport::decl(&config),
        crate::accounts::ApiProfile::decl(&config),
        crate::accounts::probe::Check::decl(&config),
        crate::accounts::probe::ValidationChecks::decl(&config),
        crate::accounts::probe::EngineValidationChecks::decl(&config),
        crate::accounts::ApiValidation::decl(&config),
        crate::accounts::ApiEngineValidation::decl(&config),
        crate::accounts::NativeAccount::decl(&config),
        crate::accounts::AccountListResult::decl(&config),
        crate::accounts::models::CatalogModel::decl(&config),
        crate::accounts::models::FeatureError::decl(&config),
        crate::accounts::models::ModelsResult::decl(&config),
        crate::accounts::config::AccountConfigDocument::decl(&config),
        crate::accounts::config::AgentAccountConfig::decl(&config),
        crate::accounts::config::AccountConfigResult::decl(&config),
        crate::accounts::sources::SourceEndpoint::decl(&config),
        crate::accounts::sources::SourceCredentialInfo::decl(&config),
        crate::accounts::sources::SourceRoute::decl(&config),
        crate::accounts::sources::ModelSource::decl(&config),
        crate::accounts::sources::SourceBindingView::decl(&config),
        crate::accounts::sources::SourceMigrationAccount::decl(&config),
        crate::accounts::sources::SourceMigration::decl(&config),
        crate::accounts::sources::SourceResult::decl(&config),
        FsEntry::decl(&config),
        FsListing::decl(&config),
        FsContent::decl(&config),
        FsWritten::decl(&config),
        FsChunk::decl(&config),
        FsDone::decl(&config),
        SearchMatch::decl(&config),
        SearchResult::decl(&config),
        ProjectSearchRequest::decl(&config),
        WorkspaceSummaryResult::decl(&config),
        GitFile::decl(&config),
        GitStatusResult::decl(&config),
        GitDiffResult::decl(&config),
        GitHistoryEntry::decl(&config),
        GitHistoryResult::decl(&config),
        GitDone::decl(&config),
        FsPathQuery::decl(&config),
        FsChunkQuery::decl(&config),
        GitDiffQuery::decl(&config),
        FsWriteRequest::decl(&config),
        FsPathRequest::decl(&config),
        FsRenameRequest::decl(&config),
        GitStageRequest::decl(&config),
        GitCommitRequest::decl(&config),
        FsPutRequest::decl(&config),
        crate::error::ErrorBody::decl(&config),
    ];
    let mut output: String = declarations
        .into_iter()
        .map(|value| {
            let value = value
                .lines()
                .map(str::trim_end)
                .collect::<Vec<_>>()
                .join("\n");
            format!("export {value}\n")
        })
        .collect();
    output.push_str(&crate::terminal::screen::width_tables());
    output
}
