use std::collections::HashMap;
use std::path::Path;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Duration;

use tokio::sync::{Mutex, MutexGuard, Semaphore, oneshot, watch};

use super::claude::{AdapterEvent, ClaudeTurn, QuestionReply, TurnOptions, spawn_turn};
use super::store::{ApprovalPolicy, PermissionMode, QueuedRow};
use super::*;
use crate::error::{Error, Result};
use crate::protocol::*;
use crate::worker::Database;

const MAX_TURNS: usize = 16;

/// Latest card state carried between card-record rewrites.
struct CardState {
    name: String,
    role: Option<String>,
    task: Option<String>,
    created_at: i64,
    status: String,
    can_message: bool,
    summary: String,
}

/// CLI task ids are only used as opaque keys by the renderer, but timeline
/// record ids must match `[A-Za-z0-9_-]{1,256}`; normalize defensively.
fn safe_owner(id: &str) -> String {
    let mut slug: String = id
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '-' || *c == '_')
        .collect();
    if slug.is_empty() {
        slug.push_str("subagent");
    }
    slug.truncate(120);
    slug
}

/// Build metadata-only attachment refs for the persisted user record. Ids are
/// generated by the daemon; bytes are never stored or re-served.
fn attachment_refs(attachments: &[AttachmentInput]) -> Vec<MessageAttachment> {
    attachments
        .iter()
        .map(|attachment| MessageAttachment {
            id: uuid::Uuid::new_v4().simple().to_string(),
            mime_type: attachment.mime_type.clone(),
            name: attachment.name.clone(),
        })
        .collect()
}

struct Handle {
    driver: Mutex<ClaudeTurn>,
    replies: Mutex<HashMap<String, oneshot::Sender<bool>>>,
    /// request id -> timeline record id of pending approvals.
    records: Mutex<HashMap<String, String>>,
    questions: Mutex<HashMap<String, QuestionPending>>,
    compact: Mutex<Option<oneshot::Sender<std::result::Result<(), String>>>>,
    /// Starts true; flipped once the turn's `result` frame has been observed.
    /// A steer delivered later cannot reach the CLI (its stdin is about to be
    /// closed), so busy-send/guide degrade to the front of the queue instead
    /// of trusting a write that the kernel pipe buffer may absorb silently.
    steerable: AtomicBool,
}

/// Pending AskUserQuestion: the blocking CLI reply plus the map from public
/// question ids (`q1`) back to the native question text used in the answer.
struct QuestionPending {
    reply: oneshot::Sender<QuestionReply>,
    native_by_id: HashMap<String, String>,
}

struct Session {
    handle: Mutex<Option<Arc<Handle>>>,
    usage: Mutex<UsageReport>,
    ended: watch::Sender<()>,
    /// Serializes drain loops so only the turn that just finished chains the
    /// queued turns (mirrors the legacy `drainingQueue` guard).
    draining: Mutex<()>,
    /// Concurrency slot; released when the session entry is dropped.
    #[allow(dead_code)]
    permit: Mutex<Option<tokio::sync::OwnedSemaphorePermit>>,
}

struct State {
    database: Database,
    entries: Mutex<HashMap<String, Arc<Session>>>,
    slots: Arc<Semaphore>,
    closed: AtomicBool,
    failed: AtomicBool,
    changed: watch::Sender<u64>,
}

#[derive(Clone)]
pub struct Agents(Arc<State>);

impl Agents {
    pub fn new(database: Database) -> Self {
        Self(Arc::new(State {
            database,
            entries: Mutex::new(HashMap::new()),
            slots: Arc::new(Semaphore::new(MAX_TURNS)),
            closed: AtomicBool::new(false),
            failed: AtomicBool::new(false),
            changed: watch::channel(0).0,
        }))
    }

    pub fn count(&self) -> usize {
        MAX_TURNS - self.0.slots.available_permits()
    }

    pub(crate) fn changes(&self) -> watch::Sender<u64> {
        self.0.changed.clone()
    }

    pub fn check(&self) -> Result<()> {
        if self.0.failed.load(Ordering::Acquire) {
            Err(Error::Closed)
        } else {
            Ok(())
        }
    }

    pub async fn create(&self, input: CreateAgentSession) -> Result<SessionHead> {
        crate::database::validate_text(&input.title, 512, false)?;
        if input.workspace.len() > 4096 || input.workspace.trim().is_empty() {
            return Err(Error::Invalid("invalid workspace".into()));
        }
        if !Path::new(&input.workspace).is_absolute() {
            return Err(Error::Invalid("workspace must be absolute".into()));
        }
        if self.0.closed.load(Ordering::Acquire) {
            return Err(Error::Closed);
        }
        let workspace = tokio::task::spawn_blocking({
            let workspace = input.workspace.clone();
            move || std::fs::canonicalize(workspace)
        })
        .await
        .map_err(|_| Error::Closed)??;
        if !workspace.is_dir() {
            return Err(Error::Invalid("workspace is not a directory".into()));
        }
        let workspace = workspace
            .to_str()
            .ok_or_else(|| Error::Invalid("workspace must be Unicode".into()))?
            .to_owned();
        let permit = self
            .0
            .slots
            .clone()
            .try_acquire_owned()
            .map_err(|_| Error::Busy)?;
        let policy = if input.auto_approve {
            ApprovalPolicy::Auto
        } else {
            ApprovalPolicy::Manual
        };
        let mut create = CreateAgentSession {
            title: input.title,
            workspace,
            auto_approve: input.auto_approve,
            model: input.model,
            effort: input.effort,
            account_id: input.account_id,
        };
        let database = self.0.database.clone();
        let data = self.0.database.directory().to_owned();
        let head = self
            .0
            .database
            .call(move |store| {
                if let Some(account_id) = create.account_id.as_deref() {
                    if let Some(message) =
                        crate::accounts::source_bound_launch_error(&database, account_id)?
                    {
                        return Err(Error::Invalid(message));
                    }
                    if account_id != crate::accounts::NATIVE_CLAUDE_ID {
                        let record = store.managed_snapshot_row(&data, account_id)?;
                        let target = crate::accounts::config::ConfigTarget {
                            account_id: record.id.clone(),
                            model: record
                                .api_profile
                                .as_ref()
                                .map(|profile| profile.model.clone()),
                            model_capabilities: record
                                .api_profile
                                .as_ref()
                                .and_then(|profile| profile.model_capabilities.clone()),
                            active_sessions: 0,
                        };
                        let (default_model, default_effort) =
                            crate::accounts::config::read_defaults(&data, &target)?;
                        let effective_default_model = target.model.clone().or(default_model);
                        let apply_default_effort = create.effort.is_none()
                            && create
                                .model
                                .as_deref()
                                .map(|model| Some(model) == effective_default_model.as_deref())
                                .unwrap_or(true);
                        if create.model.is_none() {
                            create.model = effective_default_model;
                        }
                        if apply_default_effort {
                            create.effort = default_effort;
                        }
                    }
                }
                store.create_agent_session(create, policy)
            })
            .await?;
        let (ended, _) = watch::channel(());
        self.0.entries.lock().await.insert(
            head.id.clone(),
            Arc::new(Session {
                handle: Mutex::new(None),
                usage: Mutex::new(UsageReport {
                    windows: Vec::new(),
                    ..Default::default()
                }),
                ended,
                draining: Mutex::new(()),
                permit: Mutex::new(Some(permit)),
            }),
        );
        self.publish();
        Ok(head)
    }

    async fn session_entry(&self, id: &str) -> Result<Arc<Session>> {
        crate::database::validate_id(id)?;
        self.0
            .entries
            .lock()
            .await
            .get(id)
            .cloned()
            .ok_or(Error::NotFound)
    }

    pub async fn send(
        &self,
        id: &str,
        text: String,
        delivery: Option<String>,
        attachments: Vec<AttachmentInput>,
    ) -> Result<()> {
        validate_message(&text, &attachments)?;
        let entry = self.session_entry(id).await?;
        let mut guard = entry.handle.lock().await;
        let Some(handle) = guard.clone() else {
            // Idle: start a fresh turn immediately.
            let (turn, handle) = self.launch_turn(id, text, attachments, &mut guard).await?;
            self.spawn_chain(id.to_owned(), turn, handle);
            return Ok(());
        };
        // Busy turn: either steer the live CLI or park the message in the
        // persistent queue for the turn-end drain.
        let row = QueuedRow {
            id: uuid::Uuid::new_v4().simple().to_string(),
            kind: if delivery.as_deref() == Some("steer") {
                "guide"
            } else {
                "queue"
            }
            .to_owned(),
            text: text.clone(),
            created_at: crate::database::now(),
            attachments,
        };
        let steering = delivery.as_deref() == Some("steer");
        if steering && handle.steerable.load(Ordering::Acquire) {
            let workspace = {
                let id = id.to_owned();
                self.0
                    .database
                    .call(move |store| Ok(store.session(&id)?.workspace))
                    .await?
            };
            let expanded = self.expand_prompt(&workspace, &text).await?;
            if handle
                .driver
                .lock()
                .await
                .steer(&expanded, &row.attachments)
                .await
                .is_ok()
            {
                self.record_steer(id, &text, &row.attachments).await?;
                self.publish();
                return Ok(());
            }
            // The current turn can no longer accept a steer (broken pipe /
            // result already emitted): degrade to the front of the queue. The
            // message and its images must not be lost.
        }
        self.enqueue(id, &row, steering).await?;
        Ok(())
    }

    async fn enqueue(&self, id: &str, row: &QueuedRow, front: bool) -> Result<()> {
        let row = row.clone();
        let id = id.to_owned();
        self.0
            .database
            .call(move |store| store.enqueue_message(&id, &row, front))
            .await?;
        self.publish();
        Ok(())
    }

    /// Persist a successfully-delivered steer as a user message immediately:
    /// it cannot be unsent, and the audit trail must show it even though no
    /// queued row exists.
    async fn record_steer(
        &self,
        id: &str,
        text: &str,
        attachments: &[AttachmentInput],
    ) -> Result<()> {
        let (turn, _native) = {
            let id = id.to_owned();
            self.0
                .database
                .call(move |store| {
                    let run = store.agent_run(&id)?;
                    Ok((run.turn, run.native_id))
                })
                .await?
        };
        let write = TimelineWrite {
            id: format!("turn{turn}-steer-{}", uuid::Uuid::new_v4().simple()),
            turn_id: format!("turn{turn}"),
            expected_revision: 0,
            body: TimelineBody::Message {
                role: MessageRole::User,
                final_answer: false,
                attachments: attachment_refs(attachments),
            },
            text: text.to_owned(),
            replace: false,
            subagent_id: None,
        };
        let id = id.to_owned();
        self.0
            .database
            .call(move |store| store.append_agent_records(&id, vec![write]))
            .await
    }

    async fn expand_prompt(&self, workspace: &str, prompt: &str) -> Result<String> {
        let workspace = workspace.to_owned();
        let prompt = prompt.to_owned();
        tokio::task::spawn_blocking(move || crate::skills::expand_prompt(&workspace, &prompt))
            .await
            .map_err(|_| Error::Closed)
    }

    /// Prepare and spawn one CLI turn, install its handle under `guard`, and
    /// return the turn number plus the handle. The caller owns chaining (it
    /// either spawns the chain task or continues the drain loop in place).
    async fn launch_turn(
        &self,
        id: &str,
        text: String,
        attachments: Vec<AttachmentInput>,
        guard: &mut MutexGuard<'_, Option<Arc<Handle>>>,
    ) -> Result<(i64, Arc<Handle>)> {
        if self.0.closed.load(Ordering::Acquire) {
            return Err(Error::Closed);
        }
        let run = {
            let id = id.to_owned();
            self.0
                .database
                .call(move |store| {
                    let run = store.agent_run(&id)?;
                    if !run.active {
                        return Err(Error::Conflict);
                    }
                    Ok(run)
                })
                .await?
        };
        let (turn, native_id) = {
            let id = id.to_owned();
            self.0
                .database
                .call(move |store| store.begin_agent_turn(&id))
                .await?
        };
        let workspace = {
            let id = id.to_owned();
            self.0
                .database
                .call(move |store| Ok(store.session(&id)?.workspace))
                .await?
        };
        // Expand @file/$skill mentions for the CLI while the stored user
        // record keeps the original text (mirrors legacy structured-session).
        let expanded = self.expand_prompt(&workspace, &text).await?;
        self.set_status(id, SessionStatus::Running).await?;
        // Persist the user's original message before invoking the provider.
        let refs = attachment_refs(&attachments);
        let user_write = TimelineWrite {
            id: format!("turn{turn}-user"),
            turn_id: format!("turn{turn}"),
            expected_revision: 0,
            body: TimelineBody::Message {
                role: MessageRole::User,
                final_answer: false,
                attachments: refs,
            },
            text,
            replace: false,
            subagent_id: None,
        };
        {
            let id = id.to_owned();
            self.0
                .database
                .call(move |store| store.append_agent_records(&id, vec![user_write]))
                .await?;
        }
        let options = TurnOptions {
            policy: run.policy,
            mode: run.mode,
            model: run.model.clone(),
            effort: run.effort.clone(),
            environment: Self::account_environment(&self.0.database, run.account_id.clone())
                .await?,
        };
        let driver = spawn_turn(
            &workspace,
            &expanded,
            &attachments,
            native_id.as_deref(),
            &options,
        )?;
        let handle = Arc::new(Handle {
            driver: Mutex::new(driver),
            replies: Mutex::new(HashMap::new()),
            records: Mutex::new(HashMap::new()),
            questions: Mutex::new(HashMap::new()),
            compact: Mutex::new(None),
            steerable: AtomicBool::new(true),
        });
        **guard = Some(handle.clone());
        Ok((turn, handle))
    }

    /// Run one turn, then drain queued messages as chained turns, all in a
    /// single task so only the turn that just finished starts the next one.
    fn spawn_chain(&self, id: String, first_turn: i64, first_handle: Arc<Handle>) {
        let runtime = self.clone();
        tokio::spawn(async move {
            let mut turn = first_turn;
            let mut handle = first_handle;
            loop {
                runtime.run_turn(id.clone(), turn, handle.clone()).await;
                let Ok(entry) = runtime.session_entry(&id).await else {
                    break;
                };
                // Hold the drain lock for the whole pop+launch window so a
                // concurrent steer/guide/send can't start a duplicate turn.
                let _drain = entry.draining.lock().await;
                let mut guard = entry.handle.lock().await;
                if guard
                    .as_ref()
                    .is_some_and(|live| Arc::ptr_eq(live, &handle))
                {
                    *guard = None;
                }
                entry.ended.send_replace(());
                runtime.publish();
                let queued = {
                    let id = id.clone();
                    runtime
                        .0
                        .database
                        .call(move |store| store.pop_message(&id))
                        .await
                };
                let Some(row) = queued.unwrap_or(None) else {
                    break;
                };
                match runtime
                    .launch_turn(&id, row.text.clone(), row.attachments.clone(), &mut guard)
                    .await
                {
                    Ok((next_turn, next_handle)) => {
                        turn = next_turn;
                        handle = next_handle;
                        // Guard drops here; run_turn runs without it, and the
                        // next loop iteration takes the drain slot again.
                    }
                    // Archive raced the pop: the queue was cleared by design
                    // (user killed the session); do not replay it.
                    Err(Error::Conflict) | Err(Error::NotFound) => break,
                    Err(Error::Closed) => {
                        // Daemon shutdown: put the popped row back so a future
                        // daemon can drain it rather than dropping the text.
                        let _ = runtime.enqueue(&id, &row, true).await;
                        break;
                    }
                    Err(error) => {
                        // Transient failure: keep the message at the front;
                        // the next user-sent turn drains it on completion.
                        let _ = runtime.enqueue(&id, &row, true).await;
                        runtime.drain_error(&id, turn, &error.to_string()).await;
                        break;
                    }
                }
            }
        });
    }

    async fn drain_error(&self, id: &str, turn: i64, message: &str) {
        let write = TimelineWrite {
            id: format!("turn{turn}-drain-error"),
            turn_id: format!("turn{turn}"),
            expected_revision: 0,
            body: TimelineBody::Error,
            text: bounded_text(message.to_owned()),
            replace: false,
            subagent_id: None,
        };
        let id = id.to_owned();
        let _ = self
            .0
            .database
            .call(move |store| store.append_agent_records(&id, vec![write]))
            .await;
        self.publish();
    }

    /// Kick the drain when a queue mutation happens while no turn is running
    /// (e.g. guideQueued on an idle session dispatches the row immediately).
    async fn kick_drain(&self, id: &str) {
        let Ok(entry) = self.session_entry(id).await else {
            return;
        };
        let runtime = self.clone();
        let id = id.to_owned();
        tokio::spawn(async move {
            let _drain = entry.draining.lock().await;
            let mut guard = entry.handle.lock().await;
            if guard.is_some() {
                return;
            }
            let row = match runtime
                .0
                .database
                .call({
                    let id = id.clone();
                    move |store| store.pop_message(&id)
                })
                .await
            {
                Ok(Some(row)) => row,
                _ => return,
            };
            match runtime
                .launch_turn(&id, row.text.clone(), row.attachments.clone(), &mut guard)
                .await
            {
                Ok((turn, handle)) => {
                    drop(guard);
                    runtime.spawn_chain(id, turn, handle);
                }
                Err(error) => {
                    let _ = runtime.enqueue(&id, &row, true).await;
                    runtime.drain_error(&id, 0, &error.to_string()).await;
                }
            }
        });
    }

    pub async fn compact(&self, id: &str, request_id: &str) -> Result<AgentControlResult> {
        crate::database::validate_id(id)?;
        let entry = self.session_entry(id).await?;
        let handle = entry.handle.lock().await.clone().ok_or(Error::Conflict)?;
        {
            let mut waiter = handle.compact.lock().await;
            if waiter.is_some() {
                return Err(Error::Busy);
            }
            let (sender, receiver) = oneshot::channel();
            *waiter = Some(sender);
            drop(waiter);
            let send_result = handle.driver.lock().await.compact().await;
            if let Err(error) = send_result {
                let _ = handle.compact.lock().await.take();
                return Err(error);
            }
            match tokio::time::timeout(Duration::from_secs(180), receiver).await {
                Ok(Ok(Ok(()))) => Ok(AgentControlResult {
                    kind: "agent.control.result".into(),
                    sid: id.to_owned(),
                    request_id: request_id.chars().take(100).collect(),
                    action: "compact".into(),
                    ok: true,
                    message: None,
                }),
                Ok(Ok(Err(message))) => Ok(AgentControlResult {
                    kind: "agent.control.result".into(),
                    sid: id.to_owned(),
                    request_id: request_id.chars().take(100).collect(),
                    action: "compact".into(),
                    ok: false,
                    message: Some(message),
                }),
                Ok(Err(_)) => Err(Error::Closed),
                Err(_) => {
                    let _ = handle.compact.lock().await.take();
                    Err(Error::Timeout)
                }
            }
        }
    }

    async fn run_turn(&self, id: String, turn: i64, handle: Arc<Handle>) {
        let mut events = {
            let mut driver = handle.driver.lock().await;
            match driver.take_events() {
                Some(events) => events,
                None => return,
            }
        };
        // Revision counters for streaming records that get rewritten in place.
        let mut revisions: HashMap<String, i64> = HashMap::new();
        // The single subagent card per Task-tool subagent is rewritten as
        // lifecycle frames arrive; keyed by native subagent id.
        let mut card_revisions: HashMap<String, i64> = HashMap::new();
        // Card metadata carried across the rewrites (the stored record body is
        // replaced wholesale on every update).
        let mut cards: HashMap<String, CardState> = HashMap::new();
        let mut pending: Vec<TimelineWrite> = Vec::new();
        let mut native_persisted = false;
        let mut interrupted = false;
        let mut failure: Option<String> = None;

        macro_rules! flush {
            () => {{
                let writes = std::mem::take(&mut pending);
                if !writes.is_empty() {
                    let result = self
                        .0
                        .database
                        .call({
                            let id = id.clone();
                            move |store| store.append_agent_records(&id, writes)
                        })
                        .await;
                    if let Err(error) = result {
                        self.0.failed.store(true, Ordering::Release);
                        failure = Some(error.to_string());
                        break;
                    }
                }
            }};
        }

        loop {
            let Some(event) = events.recv().await else {
                failure.get_or_insert_with(|| "agent stream closed".into());
                break;
            };
            match event {
                AdapterEvent::NativeId(native_id) => {
                    if !native_persisted {
                        native_persisted = true;
                        let result = {
                            let id = id.clone();
                            let native = native_id;
                            self.0
                                .database
                                .call(move |store| store.set_agent_native_id(&id, turn, &native))
                                .await
                        };
                        if result.is_err() {
                            failure = result.err().map(|error| error.to_string());
                            break;
                        }
                    }
                }
                AdapterEvent::SubagentStarted {
                    subagent,
                    name,
                    role,
                    task,
                } => {
                    let slug = safe_owner(&subagent);
                    let now = crate::database::now();
                    cards.insert(
                        slug.clone(),
                        CardState {
                            name: name.clone(),
                            role: role.clone(),
                            task: task.clone(),
                            created_at: now,
                            status: "starting".into(),
                            can_message: true,
                            summary: String::new(),
                        },
                    );
                    pending.push(TimelineWrite {
                        id: format!("card-{slug}"),
                        turn_id: format!("turn{turn}"),
                        expected_revision: 0,
                        body: TimelineBody::Subagent {
                            subagent_id: slug.clone(),
                            name,
                            role,
                            task,
                            status: "starting".into(),
                            can_message: true,
                            summary: String::new(),
                            created_at: now,
                            updated_at: now,
                        },
                        text: String::new(),
                        replace: false,
                        subagent_id: None,
                    });
                    card_revisions.insert(slug, 1);
                    flush!();
                }
                AdapterEvent::SubagentUpdate {
                    subagent,
                    status,
                    can_message,
                    summary,
                } => {
                    let slug = safe_owner(&subagent);
                    // A late progress/notification without a task_started still
                    // needs a card (matches legacy registerSubagent-on-message).
                    if !cards.contains_key(&slug) {
                        let now = crate::database::now();
                        cards.insert(
                            slug.clone(),
                            CardState {
                                name: String::new(),
                                role: None,
                                task: None,
                                created_at: now,
                                status: "starting".into(),
                                can_message: true,
                                summary: String::new(),
                            },
                        );
                    }
                    let card = cards.get_mut(&slug).expect("card state inserted above");
                    card.status = status.to_owned();
                    card.can_message = can_message;
                    if let Some(text) = summary {
                        card.summary = bounded_text(text);
                    }
                    let CardState {
                        name,
                        role,
                        task,
                        created_at,
                        status: card_status,
                        can_message: card_can,
                        summary: card_summary,
                    } = &*card;
                    let created = !card_revisions.contains_key(&slug);
                    let revision = card_revisions.get(&slug).copied().unwrap_or(0);
                    pending.push(TimelineWrite {
                        id: format!("card-{slug}"),
                        turn_id: format!("turn{turn}"),
                        expected_revision: if created { 0 } else { revision },
                        body: TimelineBody::Subagent {
                            subagent_id: slug.clone(),
                            name: name.clone(),
                            role: role.clone(),
                            task: task.clone(),
                            status: card_status.clone(),
                            can_message: *card_can,
                            summary: card_summary.clone(),
                            created_at: *created_at,
                            updated_at: crate::database::now(),
                        },
                        text: String::new(),
                        replace: false,
                        subagent_id: None,
                    });
                    card_revisions.insert(slug.clone(), revision + 1);
                    flush!();
                }
                AdapterEvent::Text { subagent, text } => {
                    let owner = subagent.map(|value| safe_owner(&value));
                    let record = match &owner {
                        Some(slug) => format!("sub-{slug}-turn{turn}-answer"),
                        None => format!("turn{turn}-answer"),
                    };
                    let revision = revisions.get(&record).copied().unwrap_or(0);
                    pending.push(TimelineWrite {
                        id: record.clone(),
                        turn_id: format!("turn{turn}"),
                        expected_revision: revision,
                        body: TimelineBody::Message {
                            role: MessageRole::Assistant,
                            final_answer: true,
                            attachments: Vec::new(),
                        },
                        text: bounded_text(text),
                        replace: true,
                        subagent_id: owner,
                    });
                    revisions.insert(record, revision + 1);
                    flush!();
                }
                AdapterEvent::Thinking { subagent, text } => {
                    let owner = subagent.map(|value| safe_owner(&value));
                    let record = match &owner {
                        Some(slug) => format!("sub-{slug}-turn{turn}-reasoning"),
                        None => format!("turn{turn}-reasoning"),
                    };
                    let revision = revisions.get(&record).copied().unwrap_or(0);
                    pending.push(TimelineWrite {
                        id: record.clone(),
                        turn_id: format!("turn{turn}"),
                        expected_revision: revision,
                        body: TimelineBody::Reasoning,
                        text: bounded_text(text),
                        replace: true,
                        subagent_id: owner,
                    });
                    revisions.insert(record, revision + 1);
                    flush!();
                }
                AdapterEvent::ToolCall {
                    subagent,
                    call_id,
                    name,
                    summary,
                } => {
                    let owner = subagent.map(|value| safe_owner(&value));
                    let record = match &owner {
                        Some(slug) => format!("sub-{slug}-{call_id}"),
                        None => call_id.clone(),
                    };
                    pending.push(TimelineWrite {
                        id: record.clone(),
                        turn_id: format!("turn{turn}"),
                        expected_revision: 0,
                        body: TimelineBody::Tool {
                            name,
                            state: ToolState::Running,
                            summary,
                        },
                        text: String::new(),
                        replace: false,
                        subagent_id: owner,
                    });
                    revisions.insert(record, 1);
                    flush!();
                }
                AdapterEvent::ToolResult {
                    subagent,
                    call_id,
                    name,
                    summary,
                    error,
                } => {
                    let owner = subagent.map(|value| safe_owner(&value));
                    let record = match &owner {
                        Some(slug) => format!("sub-{slug}-{call_id}"),
                        None => call_id.clone(),
                    };
                    let revision = revisions.get(&record).copied().unwrap_or(1);
                    pending.push(TimelineWrite {
                        id: record.clone(),
                        turn_id: format!("turn{turn}"),
                        expected_revision: revision,
                        body: TimelineBody::Tool {
                            name,
                            state: if error {
                                ToolState::Failed
                            } else {
                                ToolState::Success
                            },
                            summary: String::new(),
                        },
                        text: summary,
                        replace: false,
                        subagent_id: owner,
                    });
                    revisions.insert(record, revision + 1);
                    flush!();
                }
                AdapterEvent::Permission {
                    subagent,
                    request_id,
                    tool,
                    summary,
                    reply,
                } => {
                    flush!();
                    // Approvals stay on the main timeline so they can be
                    // answered there; the subagent id rides along as metadata
                    // and the detail pane picks them up via body.subagent.
                    let record_id = format!("turn{turn}-perm-{request_id}");
                    handle
                        .replies
                        .lock()
                        .await
                        .insert(request_id.clone(), reply);
                    handle
                        .records
                        .lock()
                        .await
                        .insert(request_id.clone(), record_id.clone());
                    let write = TimelineWrite {
                        id: record_id,
                        turn_id: format!("turn{turn}"),
                        expected_revision: 0,
                        body: TimelineBody::PermissionRequest {
                            request_id,
                            tool,
                            resolved: false,
                            subagent,
                        },
                        text: summary,
                        replace: false,
                        subagent_id: None,
                    };
                    let result = self
                        .0
                        .database
                        .call({
                            let id = id.clone();
                            move |store| store.append_agent_records(&id, vec![write])
                        })
                        .await;
                    if result.is_err() {
                        failure = result.err().map(|error| error.to_string());
                        break;
                    }
                    self.set_status(&id, SessionStatus::WaitingPermission)
                        .await
                        .ok();
                }
                AdapterEvent::Question {
                    subagent,
                    request_id,
                    questions,
                    reply,
                } => {
                    flush!();
                    let record_id = format!("turn{turn}-q-{request_id}");
                    let native_by_id = questions
                        .iter()
                        .map(|spec| (spec.id.clone(), spec.native_question.clone()))
                        .collect::<HashMap<_, _>>();
                    let payload = questions
                        .into_iter()
                        .map(|spec| AgentQuestion {
                            id: spec.id,
                            header: spec.header,
                            question: spec.question,
                            options: spec
                                .options
                                .into_iter()
                                .map(|option| QuestionOption {
                                    label: option.label,
                                    description: option.description,
                                    preview: option.preview,
                                })
                                .collect(),
                            multi_select: spec.multi_select,
                            allow_other: true,
                        })
                        .collect::<Vec<_>>();
                    handle.questions.lock().await.insert(
                        request_id.clone(),
                        QuestionPending {
                            reply,
                            native_by_id,
                        },
                    );
                    // The records map is shared with approvals; the `q:`
                    // prefix keeps the two request-id spaces apart.
                    handle
                        .records
                        .lock()
                        .await
                        .insert(format!("q:{request_id}"), record_id.clone());
                    let write = TimelineWrite {
                        id: record_id,
                        turn_id: format!("turn{turn}"),
                        expected_revision: 0,
                        body: TimelineBody::Question {
                            request_id,
                            questions: payload,
                            resolved: false,
                            subagent,
                        },
                        text: String::new(),
                        replace: false,
                        subagent_id: None,
                    };
                    let result = self
                        .0
                        .database
                        .call({
                            let id = id.clone();
                            move |store| store.append_agent_records(&id, vec![write])
                        })
                        .await;
                    if result.is_err() {
                        failure = result.err().map(|error| error.to_string());
                        break;
                    }
                    self.set_status(&id, SessionStatus::WaitingInput).await.ok();
                }
                AdapterEvent::Compact { ok, message } => {
                    if let Some(waiter) = handle.compact.lock().await.take() {
                        let _ = waiter.send(if ok { Ok(()) } else { Err(message.clone()) });
                    }
                    if ok {
                        pending.push(TimelineWrite {
                            id: format!("turn{turn}-compact-{}", uuid::Uuid::new_v4().simple()),
                            turn_id: format!("turn{turn}"),
                            expected_revision: 0,
                            body: TimelineBody::TurnEnd {
                                finish: "compact".into(),
                            },
                            text: String::new(),
                            replace: false,
                            subagent_id: None,
                        });
                        flush!();
                    } else {
                        pending.push(TimelineWrite {
                            id: format!("turn{turn}-compact-error"),
                            turn_id: format!("turn{turn}"),
                            expected_revision: 0,
                            body: TimelineBody::Error,
                            text: bounded_text(message),
                            replace: false,
                            subagent_id: None,
                        });
                        flush!();
                    }
                }
                AdapterEvent::Finish {
                    interrupted: was_interrupted,
                    error,
                    cost_usd,
                    input_tokens,
                    output_tokens,
                } => {
                    handle.steerable.store(false, Ordering::Release);
                    let has_usage = cost_usd.unwrap_or(0.0) > 0.0
                        || input_tokens.unwrap_or(0) > 0
                        || output_tokens.unwrap_or(0) > 0;
                    if has_usage && let Ok(session) = self.session_entry(&id).await {
                        let mut usage = session.usage.lock().await;
                        usage.cost_usd =
                            Some(usage.cost_usd.unwrap_or(0.0) + cost_usd.unwrap_or(0.0));
                        usage.input_tokens =
                            Some(usage.input_tokens.unwrap_or(0) + input_tokens.unwrap_or(0));
                        usage.output_tokens =
                            Some(usage.output_tokens.unwrap_or(0) + output_tokens.unwrap_or(0));
                    }
                    interrupted = was_interrupted;
                    failure = error;
                    break;
                }
            }
        }

        if let Some(waiter) = handle.compact.lock().await.take() {
            let _ = waiter.send(Err(failure
                .clone()
                .unwrap_or_else(|| "Claude 上下文压缩未完成".into())));
        }

        // Terminal records: error (if any) and the turn end marker.
        let finish = if interrupted {
            "interrupted"
        } else if failure.is_some() {
            "failed"
        } else {
            "completed"
        };
        let mut terminal = Vec::new();
        if let Some(message) = &failure {
            terminal.push(TimelineWrite {
                id: format!("turn{turn}-error"),
                turn_id: format!("turn{turn}"),
                expected_revision: 0,
                body: TimelineBody::Error,
                text: bounded_text(message.clone()),
                replace: false,
                subagent_id: None,
            });
        }
        terminal.push(TimelineWrite {
            id: format!("turn{turn}-end"),
            turn_id: format!("turn{turn}"),
            expected_revision: 0,
            body: TimelineBody::TurnEnd {
                finish: finish.into(),
            },
            text: String::new(),
            replace: false,
            subagent_id: None,
        });
        let _ = {
            let id = id.clone();
            self.0
                .database
                .call(move |store| store.append_agent_records(&id, terminal))
                .await
        };
        let status = if failure.is_some() {
            SessionStatus::Failed
        } else {
            SessionStatus::Idle
        };
        // Skip the write (and publish) when the session was archived while the
        // turn was still running; archival owns the terminal status then.
        let updated = {
            let id = id.clone();
            self.0
                .database
                .call(move |store| store.finish_agent_turn_status(&id, status))
                .await
        };
        if updated.unwrap_or(false) {
            self.publish();
        }
    }

    async fn set_status(&self, id: &str, status: SessionStatus) -> Result<SessionHead> {
        let head = self
            .0
            .database
            .call({
                let id = id.to_owned();
                move |store| {
                    let head = store.session(&id)?;
                    store.update_session(
                        &id,
                        UpdateSession {
                            revision: head.revision,
                            title: None,
                            lifecycle: None,
                            status: Some(status),
                        },
                    )
                }
            })
            .await?;
        self.publish();
        Ok(head)
    }

    fn publish(&self) {
        self.0.changed.send_modify(|seq| *seq = seq.wrapping_add(1));
    }

    pub async fn respond_permission(&self, id: &str, request_id: &str, allow: bool) -> Result<()> {
        crate::database::validate_id(request_id)?;
        let entry = self.session_entry(id).await?;
        let guard = entry.handle.lock().await;
        let handle = guard.as_ref().ok_or(Error::NotFound)?;
        let reply = handle
            .replies
            .lock()
            .await
            .remove(request_id)
            .ok_or(Error::NotFound)?;
        let record_id = handle.records.lock().await.remove(request_id);
        // The translator's reply task owns the control_response frame.
        let _ = reply.send(allow);
        drop(guard);
        if let Some(record_id) = record_id {
            let id = id.to_owned();
            let result = self
                .0
                .database
                .call(move |store| store.resolve_agent_permission(&id, &record_id))
                .await;
            // A concurrently-archived session makes the record update moot.
            if !matches!(result, Err(Error::NotFound)) {
                result?;
            }
        }
        self.set_status(id, SessionStatus::Running).await?;
        Ok(())
    }

    pub async fn respond_question(
        &self,
        id: &str,
        request_id: &str,
        answers: Vec<QuestionAnswer>,
        cancelled: bool,
    ) -> Result<()> {
        crate::database::validate_id(request_id)?;
        for answer in &answers {
            crate::database::validate_id(&answer.question_id)?;
            if answer.values.iter().any(|value| value.len() > 8192) {
                return Err(Error::Invalid("answer exceeds limit".into()));
            }
        }
        let entry = self.session_entry(id).await?;
        let guard = entry.handle.lock().await;
        let handle = guard.as_ref().ok_or(Error::NotFound)?;
        let pending = handle
            .questions
            .lock()
            .await
            .remove(request_id)
            .ok_or(Error::NotFound)?;
        let record_id = handle
            .records
            .lock()
            .await
            .get(&format!("q:{request_id}"))
            .cloned();
        let native = answers
            .into_iter()
            .filter_map(|answer| {
                pending
                    .native_by_id
                    .get(&answer.question_id)
                    .map(|native| (native.clone(), answer.values.join(", ")))
            })
            .collect::<HashMap<_, _>>();
        // Dropping would deny; an explicit cancel still allows with {}.
        let _ = pending.reply.send(QuestionReply {
            answers: native,
            cancelled,
        });
        drop(guard);
        if let Some(record_id) = record_id {
            let id = id.to_owned();
            let result = self
                .0
                .database
                .call(move |store| store.resolve_agent_question(&id, &record_id))
                .await;
            if !matches!(result, Err(Error::NotFound)) {
                result?;
            }
        }
        self.set_status(id, SessionStatus::Running).await?;
        Ok(())
    }

    /// Pending messages for one session (desktop "待发送" list).
    pub async fn queue(&self, id: &str) -> Result<Vec<QueuedMessage>> {
        crate::database::validate_id(id)?;
        let id = id.to_owned();
        let rows = self
            .0
            .database
            .call(move |store| store.message_queue(&id))
            .await?;
        Ok(rows
            .into_iter()
            .map(|row| QueuedMessage {
                id: row.id,
                text: row.text,
                kind: row.kind,
                created_at: row.created_at,
                attachment_count: row.attachments.len(),
            })
            .collect())
    }

    /// Non-empty queues across all active sessions (session-list projection).
    pub async fn queues(&self) -> Result<AgentQueues> {
        let rows = self.0.database.call(|store| store.message_queues()).await?;
        Ok(AgentQueues {
            queues: rows
                .into_iter()
                .map(|(session_id, items)| AgentQueue {
                    session_id,
                    items: items
                        .into_iter()
                        .map(|row| QueuedMessage {
                            id: row.id,
                            text: row.text,
                            kind: row.kind,
                            created_at: row.created_at,
                            attachment_count: row.attachments.len(),
                        })
                        .collect(),
                })
                .collect(),
        })
    }

    /// Cancel a message that has not been dispatched yet. A steer that was
    /// already delivered has no queue row and cannot be withdrawn.
    pub async fn remove_queued(&self, id: &str, queue_id: &str) -> Result<()> {
        let id = id.to_owned();
        let queue_id = queue_id.to_owned();
        self.0
            .database
            .call(move |store| store.remove_message(&id, &queue_id))
            .await?;
        self.publish();
        Ok(())
    }

    /// Upgrade a queued message into a live steer. When the current turn
    /// cannot accept it (idle, or the CLI pipe is gone) the row moves to the
    /// front of the queue and is dispatched first on the next drain; the
    /// message text is never lost.
    pub async fn guide_queued(&self, id: &str, queue_id: &str) -> Result<()> {
        crate::database::validate_id(queue_id)?;
        let entry = self.session_entry(id).await?;
        let row = {
            let id = id.to_owned();
            let queue_id = queue_id.to_owned();
            let items = self
                .0
                .database
                .call(move |store| store.message_queue(&id))
                .await?;
            items
                .into_iter()
                .find(|item| item.id == queue_id)
                .ok_or(Error::NotFound)?
        };
        let mut steered = false;
        let guard = entry.handle.lock().await;
        if let Some(handle) = guard.as_ref()
            && handle.steerable.load(Ordering::Acquire)
        {
            let workspace = {
                let id = id.to_owned();
                self.0
                    .database
                    .call(move |store| Ok(store.session(&id)?.workspace))
                    .await?
            };
            let expanded = self.expand_prompt(&workspace, &row.text).await?;
            if handle
                .driver
                .lock()
                .await
                .steer(&expanded, &row.attachments)
                .await
                .is_ok()
            {
                steered = true;
            }
        }
        drop(guard);
        if steered {
            // The steer reached the CLI: delete the row and audit the message.
            let removed_id = id.to_owned();
            let removed_qid = queue_id.to_owned();
            let removed = self
                .0
                .database
                .call(move |store| store.remove_message(&removed_id, &removed_qid))
                .await;
            if matches!(removed, Err(Error::NotFound)) {
                // A concurrent removal (other client) still must record the
                // text that was already steered into the CLI.
            } else {
                removed?;
            }
            self.record_steer(id, &row.text, &row.attachments).await?;
            self.publish();
            return Ok(());
        }
        // Not steered: mark guide and move to the front, then kick the drain
        // in case the turn ended while we were trying.
        let guided_id = id.to_owned();
        let guided_qid = queue_id.to_owned();
        self.0
            .database
            .call(move |store| store.guide_message(&guided_id, &guided_qid))
            .await?;
        self.publish();
        drop(entry);
        self.kick_drain(id).await;
        Ok(())
    }

    /// Fetch the launch model catalog by speaking the CLI's headless
    /// `initialize` handshake (no user turn runs). Every request probes the
    /// CLI fresh, matching the legacy node adapter.
    pub async fn launch_catalog() -> Result<LaunchModelCatalog> {
        let models = super::claude::fetch_launch_catalog(&[]).await?;
        Ok(LaunchModelCatalog {
            current_model: models.first().map(|model| model.id.clone()),
            models,
        })
    }

    /// Catalog for a specific account: managed accounts probe through their
    /// isolated config root, so the directory reflects their own identity.
    pub async fn launch_catalog_for(&self, account_id: Option<&str>) -> Result<LaunchModelCatalog> {
        let account_id = match account_id {
            None | Some(crate::accounts::NATIVE_CLAUDE_ID) => None,
            Some(id) => {
                crate::database::validate_id(id)?;
                let id_owned = id.to_owned();
                self.0
                    .database
                    .call(move |store| Ok(store.managed_account(&id_owned)?.id))
                    .await?;
                Some(id.to_owned())
            }
        };
        let environment = Self::account_environment(&self.0.database, account_id.clone()).await?;
        // Profile accounts pin exactly one model through the profile itself;
        // never spawn the headless CLI catalog probe against their gateway.
        if let Some(id) = account_id.as_deref() {
            let data = self.0.database.directory().to_owned();
            let id = id.to_owned();
            let profile = self
                .0
                .database
                .call(move |store| Ok(store.managed_snapshot_row(&data, &id)?.api_profile))
                .await?;
            if let Some(profile) = profile {
                let efforts = profile
                    .model_capabilities
                    .as_ref()
                    .and_then(|caps| caps.supported_efforts.clone())
                    .unwrap_or_default();
                let model = profile.model.clone();
                return Ok(LaunchModelCatalog {
                    current_model: Some(model.clone()),
                    models: vec![LaunchModelInfo {
                        id: model,
                        label: profile.model.clone(),
                        description: None,
                        supported_efforts: efforts,
                        is_default: true,
                    }],
                });
            }
        }
        let models = super::claude::fetch_launch_catalog(&environment).await?;
        Ok(LaunchModelCatalog {
            current_model: models.first().map(|model| model.id.clone()),
            models,
        })
    }

    /// Private environment overrides for a session's bound account (empty for
    /// the native environment). Profile accounts get the isolated API-key
    /// profile environment; legacy managed accounts the OAuth/imported-key one.
    /// Credential files are read off the async pool.
    async fn account_environment(
        database: &crate::worker::Database,
        account_id: Option<String>,
    ) -> Result<Vec<(String, String)>> {
        let Some(id) = account_id else {
            return Ok(Vec::new());
        };
        let data = database.directory().to_owned();
        let db = database.clone();
        let profile_id = id.clone();
        let profile_data = data.clone();
        let profile = db
            .call(move |store| {
                Ok(store
                    .managed_snapshot_row(&profile_data, &profile_id)?
                    .api_profile)
            })
            .await?;
        tokio::task::spawn_blocking(move || match profile {
            Some(profile) => {
                crate::accounts::managed::profile_account_environment(&data, &id, &profile)
            }
            None => crate::accounts::managed::claude_environment(&data, &id, false),
        })
        .await
        .map_err(|_| Error::Closed)?
    }

    pub async fn usage(&self, id: &str) -> Result<Option<UsageReport>> {
        let entry = self.session_entry(id).await?;
        let report = entry.usage.lock().await.clone();
        if report.cost_usd.unwrap_or(0.0) == 0.0
            && report.input_tokens.unwrap_or(0) == 0
            && report.output_tokens.unwrap_or(0) == 0
            && report.windows.is_empty()
            && report.subscription.is_none()
        {
            Ok(None)
        } else {
            Ok(Some(report))
        }
    }

    pub async fn account_usage(&self) -> Result<Vec<UsageAccount>> {
        let snapshot = crate::accounts::list_accounts(&self.0.database, "usage").await?;
        let mut sessions = Vec::new();
        for (id, entry) in self.0.entries.lock().await.iter() {
            let run = self
                .0
                .database
                .call({
                    let id = id.clone();
                    move |store| store.agent_run(&id)
                })
                .await?;
            sessions.push((run.account_id, run.agent, entry.clone()));
        }
        let mut accounts = Vec::new();
        for account in snapshot
            .accounts
            .into_iter()
            .filter(|row| row.status != crate::accounts::AccountStatus::Unavailable)
        {
            let live = sessions.iter().find(|(account_id, agent, _)| {
                *agent == account.agent
                    && (account_id.as_deref() == Some(account.id.as_str())
                        || (account_id.is_none() && !account.managed))
            });
            let report = if let Some((_, _, entry)) = live {
                let report = entry.usage.lock().await.clone();
                (report.cost_usd.unwrap_or(0.0) > 0.0
                    || report.input_tokens.unwrap_or(0) > 0
                    || report.output_tokens.unwrap_or(0) > 0
                    || !report.windows.is_empty()
                    || report.subscription.is_some())
                .then_some(report)
            } else {
                None
            };
            let source = if account.api_profile.is_some()
                || account
                    .auth_method
                    .as_deref()
                    .is_some_and(|value| value.to_ascii_lowercase().contains("api"))
            {
                "api"
            } else if report
                .as_ref()
                .and_then(|value| value.subscription.as_ref())
                .is_some()
                || account.status == crate::accounts::AccountStatus::SignedIn
            {
                "subscription"
            } else {
                "unknown"
            }
            .to_owned();
            let available = report.is_some() || source == "api";
            let reason = if report.is_none() {
                Some(
                    if source == "api" {
                        "API 模型由服务商按 API 用量计费，不提供订阅窗口。"
                    } else {
                        "暂时读不到账号额度，请确认 CLI 已登录并刷新。"
                    }
                    .into(),
                )
            } else if report
                .as_ref()
                .is_some_and(|value| value.windows.is_empty())
            {
                Some("这个后端不提供套餐限流窗口。".into())
            } else {
                None
            };
            accounts.push(UsageAccount {
                agent: account.agent,
                account_id: Some(account.id),
                account_name: Some(account.name),
                source: Some(source),
                available,
                report: report.unwrap_or_else(|| UsageReport {
                    windows: Vec::new(),
                    ..Default::default()
                }),
                reason,
            });
        }
        match super::usage::read_native_codex_usage(self.0.database.directory()).await {
            Ok(Some(report)) => {
                accounts.push(UsageAccount {
                    agent: crate::protocol::AgentKind::Codex,
                    account_id: Some(super::usage::NATIVE_CODEX_ID.into()),
                    account_name: Some("本机默认".into()),
                    source: Some("subscription".into()),
                    available: true,
                    reason: if report.windows.is_empty() {
                        Some("这个后端不提供套餐限流窗口。".into())
                    } else {
                        None
                    },
                    report,
                });
            }
            Ok(None) => {
                accounts.push(UsageAccount {
                    agent: crate::protocol::AgentKind::Codex,
                    account_id: Some(super::usage::NATIVE_CODEX_ID.into()),
                    account_name: Some("本机默认".into()),
                    source: Some("unknown".into()),
                    available: false,
                    report: UsageReport {
                        windows: Vec::new(),
                        ..Default::default()
                    },
                    reason: Some("暂时读不到账号额度，请确认 Codex CLI 已登录并刷新。".into()),
                });
            }
            Err(Error::Feature(code, _)) if code == "agent_unavailable" => {}
            Err(_) => {
                accounts.push(UsageAccount {
                    agent: crate::protocol::AgentKind::Codex,
                    account_id: Some(super::usage::NATIVE_CODEX_ID.into()),
                    account_name: Some("本机默认".into()),
                    source: Some("unknown".into()),
                    available: false,
                    report: UsageReport {
                        windows: Vec::new(),
                        ..Default::default()
                    },
                    reason: Some("暂时读不到账号额度，请确认 Codex CLI 已登录并刷新。".into()),
                });
            }
        }
        accounts.sort_by(|a, b| {
            let score = |account: &UsageAccount| -> f64 {
                if !account.available {
                    return -1.0;
                }
                account
                    .report
                    .windows
                    .iter()
                    .map(|window| window.utilization)
                    .fold(0.0, f64::max)
            };
            score(b)
                .partial_cmp(&score(a))
                .unwrap_or(std::cmp::Ordering::Equal)
        });
        Ok(accounts)
    }

    /// Current collaboration mode (`default`/`plan`).
    pub async fn mode(&self, id: &str) -> Result<PermissionMode> {
        let id = id.to_owned();
        self.0
            .database
            .call(move |store| Ok(store.agent_run(&id)?.mode))
            .await
    }

    pub async fn set_approval_policy(&self, id: &str, policy: ApprovalPolicy) -> Result<()> {
        let id = id.to_owned();
        self.0
            .database
            .call(move |store| store.set_approval_policy(&id, policy))
            .await?;
        self.publish();
        Ok(())
    }

    /// Switch the collaboration mode. The change applies to the next turn;
    /// a turn already running keeps the mode it started with.
    pub async fn set_mode(&self, id: &str, mode: PermissionMode) -> Result<()> {
        let id = id.to_owned();
        self.0
            .database
            .call(move |store| store.set_agent_mode(&id, mode))
            .await?;
        self.publish();
        Ok(())
    }

    /// In-session model catalog. The catalog itself comes fresh from the
    /// headless `initialize` handshake; currentModel/currentEffort are the
    /// session's persisted selection.
    pub async fn models(&self, id: &str) -> Result<AgentModelCatalog> {
        let id = id.to_owned();
        let run = self
            .0
            .database
            .call(move |store| store.agent_run(&id))
            .await?;
        if !run.active {
            return Err(Error::Conflict);
        }
        let environment =
            Self::account_environment(&self.0.database, run.account_id.clone()).await?;
        // Profile sessions expose the pinned model only.
        if let Some(id) = run.account_id.as_deref() {
            let data = self.0.database.directory().to_owned();
            let id = id.to_owned();
            let profile = self
                .0
                .database
                .call(move |store| Ok(store.managed_snapshot_row(&data, &id)?.api_profile))
                .await?;
            if let Some(profile) = profile {
                let current = profile.model.clone();
                return Ok(AgentModelCatalog {
                    models: vec![super::LaunchModelInfo {
                        id: profile.model.clone(),
                        label: profile.model.clone(),
                        description: None,
                        supported_efforts: profile
                            .model_capabilities
                            .as_ref()
                            .and_then(|caps| caps.supported_efforts.clone())
                            .unwrap_or_default(),
                        is_default: true,
                    }],
                    current_model: Some(current),
                    current_effort: run.effort,
                });
            }
        }
        let models = super::claude::fetch_launch_catalog(&environment).await?;
        let current_model = run
            .model
            .or_else(|| models.first().map(|model| model.id.clone()));
        Ok(AgentModelCatalog {
            models,
            current_model,
            current_effort: run.effort,
        })
    }

    /// Switch the session's model/effort. Validated against the fresh
    /// catalog, persisted for every later chained turn, and forwarded to a
    /// live turn through the CLI control channel.
    pub async fn set_model(
        &self,
        id: &str,
        model: String,
        effort: Option<String>,
    ) -> Result<AgentModelSelectionResult> {
        crate::database::validate_id(id)?;
        let effort = effort
            .map(|value| value.trim().to_owned())
            .filter(|value| !value.is_empty());
        if model.trim().is_empty()
            || model.chars().count() > 160
            || model.chars().any(|c| c.is_control())
        {
            return Err(Error::Invalid("模型无效".into()));
        }
        if let Some(effort) = &effort
            && (effort.chars().count() > 80 || effort.chars().any(|c| c.is_control()))
        {
            return Err(Error::Invalid("思考强度无效".into()));
        }
        let id_for_env = id.to_owned();
        let account_id = self
            .0
            .database
            .call(move |store| Ok(store.agent_run(&id_for_env)?.account_id))
            .await?;
        let environment = Self::account_environment(&self.0.database, account_id.clone()).await?;
        // Profile sessions expose only the pinned model and never switch.
        if let Some(id) = account_id {
            let data = self.0.database.directory().to_owned();
            let profile = self
                .0
                .database
                .call(move |store| Ok(store.managed_snapshot_row(&data, &id)?.api_profile))
                .await?;
            if profile.is_some() {
                return Err(Error::Invalid(
                    "第三方 API Profile 的模型由 Profile 固定，无法在会话内切换".into(),
                ));
            }
        }
        let catalog = super::claude::fetch_launch_catalog(&environment).await?;
        let selected = catalog
            .iter()
            .find(|entry| entry.id == model)
            .ok_or_else(|| Error::Invalid(format!("Claude 模型不可用:{model}")))?;
        if let Some(effort) = &effort
            && !selected
                .supported_efforts
                .iter()
                .any(|level| level == effort)
        {
            return Err(Error::Invalid(format!("{model} 不支持推理强度 {effort}")));
        }
        let id_owned = id.to_owned();
        let model_owned = model.clone();
        let effort_owned = effort.clone();
        let (model, effort) = self
            .0
            .database
            .call(move |store| {
                store.set_agent_selection(&id_owned, &model_owned, effort_owned.as_deref())
            })
            .await?;

        // Forward to a running turn. A closed pipe means the turn is already
        // ending; the persisted selection still applies to the next turn.
        if let Ok(entry) = self.session_entry(id).await {
            let guard = entry.handle.lock().await;
            if let Some(handle) = guard.as_ref() {
                match handle
                    .driver
                    .lock()
                    .await
                    .apply_selection(&model, effort.as_deref())
                    .await
                {
                    Ok(()) | Err(Error::Closed) => {}
                    Err(error) => return Err(error),
                }
            }
        }
        self.publish();
        Ok(AgentModelSelectionResult {
            current_model: model,
            current_effort: effort,
        })
    }

    /// Active sessions' model/mode control flags for the desktop projection.
    pub async fn controls(&self) -> Result<AgentControlsProjection> {
        let controls = self.0.database.call(|store| store.agent_controls()).await?;
        Ok(AgentControlsProjection { controls })
    }

    /// On-demand transcript for a Task-tool subagent's "查看执行详情" pane.
    pub async fn subagent_snapshot(
        &self,
        id: &str,
        subagent: &str,
    ) -> Result<crate::agent::SubagentSnapshot> {
        let id = id.to_owned();
        let subagent = subagent.to_owned();
        self.0
            .database
            .call(move |store| store.subagent_snapshot(&id, &subagent))
            .await
    }

    pub async fn interrupt(&self, id: &str) -> Result<()> {
        let entry = self.session_entry(id).await?;
        let guard = entry.handle.lock().await;
        let handle = guard.as_ref().ok_or(Error::NotFound)?;
        // Any unresolved approvals are rejected and pending questions are
        // denied when the turn is interrupted.
        let pending: Vec<_> = std::mem::take(&mut *handle.replies.lock().await)
            .into_iter()
            .collect();
        std::mem::take(&mut *handle.questions.lock().await);
        std::mem::take(&mut *handle.records.lock().await);
        for (_request_id, reply) in pending {
            // The translator's reply task writes the deny frame.
            let _ = reply.send(false);
        }
        drop(guard);
        let resolved = {
            let id = id.to_owned();
            self.0
                .database
                .call(move |store| store.resolve_all_agent_requests(&id))
                .await?
        };
        if resolved > 0 {
            self.publish();
        }
        // Tell the CLI to stop after it finishes the current response.
        let entry = self.session_entry(id).await?;
        if let Some(handle) = entry.handle.lock().await.as_ref() {
            handle.driver.lock().await.interrupt();
        }
        Ok(())
    }

    pub async fn close(&self, id: &str) -> Result<()> {
        // Archive first: active=0 plus the queue delete closes the window in
        // which a finishing chain could pop a queued row and relaunch a CLI
        // for a session the user just killed.
        let archived = id.to_owned();
        self.0
            .database
            .call(move |store| store.archive_agent_session(&archived, true))
            .await?;
        if let Ok(entry) = self.session_entry(id).await {
            if let Some(handle) = entry.handle.lock().await.take() {
                let pending = std::mem::take(&mut *handle.replies.lock().await);
                // Dropping pending question senders makes the translator
                // answer deny; no explicit send needed.
                std::mem::take(&mut *handle.questions.lock().await);
                for (_request_id, reply) in pending {
                    // The translator's reply task owns the deny frame; sending
                    // here is enough, calling driver.respond_permission too
                    // would write the frame twice.
                    let _ = reply.send(false);
                }
                handle.driver.lock().await.kill();
                let mut ended = entry.ended.subscribe();
                let _ = tokio::time::timeout(Duration::from_secs(3), ended.changed()).await;
            }
            self.0.entries.lock().await.remove(id);
        }
        self.publish();
        Ok(())
    }

    /// Archive runs left active by a previous daemon process. The provider
    /// process is gone with that daemon, so turns are never replayed.
    pub async fn recover(&self) -> Result<usize> {
        let ids: Vec<String> = self
            .0
            .database
            .call(|store| {
                let mut statement = store.connection.prepare(
                    "SELECT session_id FROM agent_runs WHERE active=1 ORDER BY session_id",
                )?;
                let ids = statement
                    .query_map([], |row| row.get::<_, String>(0))?
                    .collect::<std::result::Result<Vec<_>, _>>()?;
                Ok(ids)
            })
            .await?;
        for id in &ids {
            let id = id.clone();
            self.0
                .database
                .call(move |store| store.archive_agent_session(&id, true))
                .await?;
        }
        Ok(ids.len())
    }

    pub async fn shutdown(&self) -> Result<()> {
        self.0.closed.store(true, Ordering::Release);
        let sessions: Vec<Arc<Session>> = self.0.entries.lock().await.values().cloned().collect();
        for session in &sessions {
            if let Some(handle) = session.handle.lock().await.take() {
                let pending = std::mem::take(&mut *handle.replies.lock().await);
                std::mem::take(&mut *handle.questions.lock().await);
                for (_request_id, reply) in pending {
                    // See close(): the translator task writes the deny frame.
                    let _ = reply.send(false);
                }
                handle.driver.lock().await.kill();
            }
        }
        for session in &sessions {
            let mut ended = session.ended.subscribe();
            let _ = tokio::time::timeout(Duration::from_secs(3), ended.changed()).await;
        }
        self.check()
    }
}

/// Cap text persisted with a single streaming rewrite.
fn bounded_text(mut text: String) -> String {
    const LIMIT: usize = 60_000;
    if text.len() <= LIMIT {
        return text;
    }
    let mut end = LIMIT;
    while !text.is_char_boundary(end) {
        end -= 1;
    }
    text.truncate(end);
    text
}
